Update ci.yml test #8 dast https

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -131,8 +131,17 @@ jobs:
           python manage.py migrate
           gunicorn --bind 0.0.0.0:8000 --timeout 180 --workers 1 InventoryMS.wsgi:application &
           sleep 20
-          curl -f http://localhost:8000/
+          echo "=== Test root ==="
+          curl -v -H "Host: localhost" http://localhost:8000/ || echo "Root FAIL"
+          
+          echo "=== Test admin ==="
+          curl -v -H "Host: localhost" http://localhost:8000/admin/ || echo "Admin FAIL"
+          
+          echo "=== Headers test ==="
+          curl -v -H "Host: localhost" -H "Origin: http://localhost:8000" http://localhost:8000/
           # Czekamy aż wstanie
+    # DEBUG requests
+
 
       - name: OWASP ZAP Baseline Scan
         uses: zaproxy/action-baseline@v0.15.0
